name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "407af675d0ebdad780782e0d728f3bcf9560647812b8c1445f87be9aea8ea0d7"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
