name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae8b2f11fcfb9ecaaa6366c8a3f59c63e293e31fbeeb94a4f726d7098a45753f"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
