name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2504ba93b1dd351f1b1367a4c4072b631afab4240045cc44393a438988bee22"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
