name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0836008f6a35821320ee62e082482b6fc9eacee8010ba805fcbbe606fcb50ec8"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
