name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c89a6dbe4607ac01724b160377ae25c1581b8b0b2753281782368b2a3b0bbf9b"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
