name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c521c4c76cfc5a93a40bdb619689918f6192bd37080a7f5b5491662404689ad4"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
