name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3661cd1746537f21f71ab2dcecfb94637819b8d2d9dabc1bfcb1687a414ee21f"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
