name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a21cd0ab3dfb7b45fbfa59cba9f9679c960d58e669319ffeea9c35285e936b0"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
