name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "803baf17f2f56f88bbf6b016fc2ff19c372b046f3b83c1282dd5c1e1da8d4a4d"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
