name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccd6397d191c9291e6301bbb585e974d133f65aa75e008149bf600179ac34bff"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
