name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcee6adec6227de3074779657d5bfb0ab6332a3f5dec824b3e87f42e1ba84f52"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
