name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0cc427575426933e38452ca6e566454e98208db84d877f1dfd3b31b679a792f"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
