name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6b69a83e20f064aa8b87607ac3c5cc83e873cc5b33af4dc3b28cf590188049f"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
