name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe619e6cb1ceee8aa4f47140a0ca09710c10518f7216dfad5a88a3517b14b035"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
