name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89056b6309b51acc9a826be9ac0c4bb91a336c7c05eb02cf048ad312b0a56837"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
