name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a1c232e2fd0b0fab72cef541568562b244b1162686019a7ad9c0d18ec974b12"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
