name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28a30e75c4d435de7679ea4376712f211bae2d4ef2ea28fb6d840fe76c862719"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
