name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a3b961366eac5e4b318ae5c06f68a15092fe751c575c2eee8f6b2ddb22cde5"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
