name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4545ba6130ebfc405c686a6193e421defa52bf85d05051d3aeeeea773f677ae"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
