name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07adec47b813272d2c6524cbb855ed189453dc643928ec4e46ea0b9ee03ef0b1"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
