name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9091d130b07526571ef4120de8e56be341e3f85ab563b43567ceeaf59d758239"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
