name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "566c6a46688e78effdadd22014eecb37ade780f8393e33206c1c52bc4fea72a1"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
