name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34f1023d89acaa6afd7e6a5555e6d34017d7c47588d9e01b258176dde70e9cc2"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
