name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c87f9fb6841c4436c49813c357ff9709680a69a3d9ba08eb09867c96970ae8f6"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
