name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e850a23d191b7009c2317b82bbe5dcc35a76a8c38141a6fc3f75ec4e1f626ef7"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
